### ISSUE TITLE
About the license notation of AlbumArtExtracor

### ISSUE THREAD

**Issue by Asteriskx** [Speyd3r/MikuSharp#14]
Hi.
I'm the author of the AlbumArtExtractor library.
You are using the library below, but it is not listed in the README.md.

https://github.com/Speyd3r/MikuSharp/blob/master/MikuSharp/Commands/Music.cs#L704-L706
https://github.com/Speyd3r/MikuSharp/blob/master/MikuSharp/Commands/Music.cs#L850-L852

Could you tell me that I use AlbumArtExtractor in the  README.md？

**Comment by Speyd3r** [comment]
Hi terribly sorry, I'll add it, I haven't looked in this repo in a while and it seems my notifications from GitHub decided to not show me this
